"""
events.py — Event class hierarchy for the event-driven backtester.

The event loop communicates between modules exclusively through Event objects
placed onto a shared queue.  The hierarchy is:

    Event (abstract base)
    ├── MarketEvent   – new bar of data is available
    ├── SignalEvent   – strategy suggests a trade direction
    ├── OrderEvent    – portfolio translates signal into a concrete order
    └── FillEvent     – execution handler simulates the fill
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class EventType(Enum):
    """Enumeration of the four event types flowing through the system."""
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"


class SignalDirection(Enum):
    """Direction encoded in a signal."""
    LONG = "LONG"
    SHORT = "SHORT"
    EXIT = "EXIT"


class OrderType(Enum):
    """Supported order types."""
    MARKET = "MKT"
    LIMIT = "LMT"


class OrderDirection(Enum):
    """Buy or sell."""
    BUY = "BUY"
    SELL = "SELL"


# ---------------------------------------------------------------------------
# Event classes
# ---------------------------------------------------------------------------

@dataclass
class Event:
    """Abstract base event. Every concrete event carries an ``event_type``."""
    event_type: EventType = field(init=False)


@dataclass
class MarketEvent(Event):
    """
    Generated by the DataHandler whenever a new bar of data becomes
    available for one or more symbols.
    """
    def __post_init__(self) -> None:
        self.event_type = EventType.MARKET


@dataclass
class SignalEvent(Event):
    """
    Emitted by a Strategy to indicate a trading signal.

    Attributes
    ----------
    symbol : str
        Ticker symbol (e.g. ``"AAPL"``).
    datetime : dt.datetime
        Timestamp of the bar that produced the signal.
    direction : SignalDirection
        LONG, SHORT, or EXIT.
    strength : float
        A scalar confidence / sizing hint (1.0 = full conviction).
    """
    symbol: str = ""
    datetime: dt.datetime = field(default_factory=dt.datetime.now)
    direction: SignalDirection = SignalDirection.LONG
    strength: float = 1.0

    def __post_init__(self) -> None:
        self.event_type = EventType.SIGNAL


@dataclass
class OrderEvent(Event):
    """
    Sent from the Portfolio to the ExecutionHandler.

    Attributes
    ----------
    symbol : str
        Ticker symbol.
    order_type : OrderType
        MKT or LMT.
    quantity : int
        Number of shares / units to trade.
    direction : OrderDirection
        BUY or SELL.
    """
    symbol: str = ""
    order_type: OrderType = OrderType.MARKET
    quantity: int = 0
    direction: OrderDirection = OrderDirection.BUY

    def __post_init__(self) -> None:
        self.event_type = EventType.ORDER

    def __repr__(self) -> str:
        return (
            f"OrderEvent(symbol={self.symbol!r}, type={self.order_type.value}, "
            f"qty={self.quantity}, dir={self.direction.value})"
        )


@dataclass
class FillEvent(Event):
    """
    Returned by the ExecutionHandler after simulating order execution.

    Attributes
    ----------
    timeindex : dt.datetime
        Timestamp of the fill.
    symbol : str
        Ticker symbol.
    exchange : str
        Exchange on which the fill occurred (default ``"BACKTEST"``).
    quantity : int
        Quantity filled.
    direction : OrderDirection
        BUY or SELL.
    fill_cost : float
        Total cost of the fill *before* commission (price × quantity).
    commission : float
        Commission charged by the simulated broker.
    slippage : float
        Slippage cost applied to this fill.
    """
    timeindex: dt.datetime = field(default_factory=dt.datetime.now)
    symbol: str = ""
    exchange: str = "BACKTEST"
    quantity: int = 0
    direction: OrderDirection = OrderDirection.BUY
    fill_cost: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0

    def __post_init__(self) -> None:
        self.event_type = EventType.FILL
