"""
tearsheet.py — Tear Sheet generator.

Produces a comprehensive HTML report containing:
    - Equity curve plot
    - Underwater (drawdown) plot
    - Monthly returns heatmap
    - Performance metrics summary table
"""

from __future__ import annotations

import os
import base64
from io import BytesIO
from typing import Dict, Optional

import matplotlib
matplotlib.use("Agg")  # Non-interactive backend

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import numpy as np
import pandas as pd

from backtester.performance import PerformanceManager


# ---------------------------------------------------------------------------
# Jinja2-free HTML template (self-contained)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Strategy Tear Sheet</title>
<style>
    :root {{
        --bg: #0f1117;
        --card: #1a1d28;
        --accent: #6366f1;
        --green: #22c55e;
        --red: #ef4444;
        --text: #e2e8f0;
        --muted: #94a3b8;
    }}
    * {{ margin:0; padding:0; box-sizing:border-box; }}
    body {{
        background: var(--bg);
        color: var(--text);
        font-family: 'Inter', 'Segoe UI', system-ui, sans-serif;
        padding: 2rem;
    }}
    h1 {{
        font-size: 2rem;
        background: linear-gradient(135deg, var(--accent), #a78bfa);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: .25rem;
    }}
    .subtitle {{ color: var(--muted); margin-bottom: 2rem; font-size: .95rem; }}
    .grid {{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
        gap: 1rem;
        margin-bottom: 2rem;
    }}
    .metric-card {{
        background: var(--card);
        border-radius: 12px;
        padding: 1.25rem;
        border: 1px solid rgba(255,255,255,.06);
    }}
    .metric-card .label {{ color: var(--muted); font-size: .8rem; text-transform: uppercase; letter-spacing: .05em; }}
    .metric-card .value {{ font-size: 1.5rem; font-weight: 700; margin-top: .35rem; }}
    .positive {{ color: var(--green); }}
    .negative {{ color: var(--red); }}
    .chart-section {{
        background: var(--card);
        border-radius: 12px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
        border: 1px solid rgba(255,255,255,.06);
    }}
    .chart-section h2 {{
        font-size: 1.1rem;
        margin-bottom: 1rem;
        color: var(--text);
    }}
    .chart-section img {{
        width: 100%;
        border-radius: 8px;
    }}
    table {{
        width: 100%;
        border-collapse: collapse;
        font-size: .9rem;
    }}
    th, td {{
        text-align: left;
        padding: .6rem 1rem;
        border-bottom: 1px solid rgba(255,255,255,.06);
    }}
    th {{ color: var(--muted); font-weight: 600; text-transform: uppercase; font-size: .75rem; letter-spacing: .05em; }}
    footer {{
        text-align: center;
        color: var(--muted);
        font-size: .75rem;
        margin-top: 3rem;
    }}
</style>
</head>
<body>
<h1>Strategy Tear Sheet</h1>
<p class="subtitle">{subtitle}</p>

<!-- Metric cards -->
<div class="grid">
{metric_cards}
</div>

<!-- Equity curve -->
<div class="chart-section">
    <h2>Equity Curve</h2>
    <img src="data:image/png;base64,{equity_plot}" alt="Equity Curve">
</div>

<!-- Drawdown -->
<div class="chart-section">
    <h2>Underwater Plot (Drawdown)</h2>
    <img src="data:image/png;base64,{drawdown_plot}" alt="Drawdown">
</div>

<!-- Monthly returns heatmap -->
<div class="chart-section">
    <h2>Monthly Returns (%)</h2>
    <img src="data:image/png;base64,{monthly_plot}" alt="Monthly Returns">
</div>

<!-- Full metrics table -->
<div class="chart-section">
    <h2>Detailed Metrics</h2>
    <table>
        <thead><tr><th>Metric</th><th>Value</th></tr></thead>
        <tbody>
{metrics_rows}
        </tbody>
    </table>
</div>

<footer>Generated by Backtesting Framework &middot; Event-Driven Engine v1.0</footer>
</body>
</html>
"""


class TearSheetGenerator:
    """
    Builds a self-contained HTML tear sheet from a PerformanceManager.

    Parameters
    ----------
    perf : PerformanceManager
        An initialised PerformanceManager with equity curve data.
    strategy_name : str
        Descriptive name shown in the report header.
    """

    def __init__(
        self, perf: PerformanceManager, strategy_name: str = "Strategy"
    ) -> None:
        self.perf = perf
        self.strategy_name = strategy_name

    # ------------------------------------------------------------------
    # Plotting helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _fig_to_base64(fig: plt.Figure) -> str:
        buf = BytesIO()
        fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                    facecolor="#1a1d28", edgecolor="none")
        plt.close(fig)
        buf.seek(0)
        return base64.b64encode(buf.read()).decode("utf-8")

    def _plot_equity_curve(self) -> str:
        equity = self.perf.equity_curve["total"]
        fig, ax = plt.subplots(figsize=(12, 4))
        ax.set_facecolor("#1a1d28")
        ax.plot(equity.index, equity.values, color="#6366f1", linewidth=1.5)
        ax.fill_between(equity.index, equity.values, alpha=0.15, color="#6366f1")
        ax.set_ylabel("Portfolio Value ($)", color="#94a3b8", fontsize=9)
        ax.tick_params(colors="#94a3b8", labelsize=8)
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
        ax.grid(True, alpha=0.1, color="#fff")
        for spine in ax.spines.values():
            spine.set_visible(False)
        return self._fig_to_base64(fig)

    def _plot_drawdown(self) -> str:
        dd = self.perf.drawdown_series()["drawdown"] * 100
        fig, ax = plt.subplots(figsize=(12, 3))
        ax.set_facecolor("#1a1d28")
        ax.fill_between(dd.index, dd.values, 0, color="#ef4444", alpha=0.45)
        ax.plot(dd.index, dd.values, color="#ef4444", linewidth=1)
        ax.set_ylabel("Drawdown (%)", color="#94a3b8", fontsize=9)
        ax.tick_params(colors="#94a3b8", labelsize=8)
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
        ax.grid(True, alpha=0.1, color="#fff")
        for spine in ax.spines.values():
            spine.set_visible(False)
        return self._fig_to_base64(fig)

    def _plot_monthly_returns(self) -> str:
        returns = self.perf.equity_curve["returns"].copy()
        returns.index = pd.to_datetime(returns.index)
        monthly = returns.resample("ME").apply(lambda x: (1 + x).prod() - 1) * 100
        pivot = pd.DataFrame({
            "year": monthly.index.year,
            "month": monthly.index.month,
            "return": monthly.values,
        })
        if pivot.empty:
            fig, ax = plt.subplots(figsize=(12, 3))
            ax.set_facecolor("#1a1d28")
            ax.text(0.5, 0.5, "Insufficient data", ha="center", va="center",
                    color="#94a3b8", transform=ax.transAxes)
            return self._fig_to_base64(fig)

        heatmap_data = pivot.pivot_table(
            index="year", columns="month", values="return", aggfunc="sum"
        )
        month_labels = [
            "Jan", "Feb", "Mar", "Apr", "May", "Jun",
            "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
        ]
        heatmap_data.columns = [
            month_labels[int(c) - 1] for c in heatmap_data.columns
        ]

        fig, ax = plt.subplots(figsize=(12, max(3, len(heatmap_data) * 0.6)))
        ax.set_facecolor("#1a1d28")
        sns.heatmap(
            heatmap_data,
            annot=True,
            fmt=".1f",
            center=0,
            cmap="RdYlGn",
            linewidths=0.5,
            linecolor="#1a1d28",
            ax=ax,
            cbar_kws={"label": "Return (%)"},
            annot_kws={"size": 8},
        )
        ax.tick_params(colors="#94a3b8", labelsize=9)
        ax.set_ylabel("")
        return self._fig_to_base64(fig)

    # ------------------------------------------------------------------
    # Metric card builder
    # ------------------------------------------------------------------
    @staticmethod
    def _metric_card(label: str, value: float, fmt: str = ".2f", pct: bool = False) -> str:
        if pct:
            display = f"{value * 100:{fmt}}%"
        else:
            display = f"{value:{fmt}}"
        css_class = "positive" if value > 0 else ("negative" if value < 0 else "")
        return (
            f'<div class="metric-card">'
            f'<div class="label">{label}</div>'
            f'<div class="value {css_class}">{display}</div>'
            f'</div>'
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def generate(self, output_path: str = "tearsheet.html") -> str:
        """
        Render the tear sheet and write it to *output_path*.

        Returns the absolute path to the generated file.
        """
        metrics = self.perf.summary()

        # Metric cards (top row)
        cards = "\n".join([
            self._metric_card("Cumulative Return", metrics["Cumulative Return"], pct=True),
            self._metric_card("Annualized Return", metrics["Annualized Return"], pct=True),
            self._metric_card("Sharpe Ratio", metrics["Sharpe Ratio"]),
            self._metric_card("Sortino Ratio", metrics["Sortino Ratio"]),
            self._metric_card("Max Drawdown", metrics["Max Drawdown"], pct=True),
            self._metric_card("Win Rate", metrics["Win Rate"], pct=True),
            self._metric_card("Profit Factor", metrics["Profit Factor"]),
            self._metric_card("Total Trades", metrics["Total Trades"], fmt=".0f"),
        ])

        # Full metrics table rows
        rows = ""
        for k, v in metrics.items():
            if isinstance(v, float):
                formatted = f"{v:.4f}"
            else:
                formatted = str(v)
            rows += f"        <tr><td>{k}</td><td>{formatted}</td></tr>\n"

        # Render plots
        equity_b64 = self._plot_equity_curve()
        dd_b64 = self._plot_drawdown()
        monthly_b64 = self._plot_monthly_returns()

        # Assemble HTML
        start_date = self.perf.equity_curve.index[0].strftime("%Y-%m-%d")
        end_date = self.perf.equity_curve.index[-1].strftime("%Y-%m-%d")
        subtitle = f"{self.strategy_name} &mdash; {start_date} to {end_date}"

        html = _HTML_TEMPLATE.format(
            subtitle=subtitle,
            metric_cards=cards,
            equity_plot=equity_b64,
            drawdown_plot=dd_b64,
            monthly_plot=monthly_b64,
            metrics_rows=rows,
        )

        abs_path = os.path.abspath(output_path)
        with open(abs_path, "w", encoding="utf-8") as f:
            f.write(html)
        return abs_path
